version: '3.8'

services:
  web-video-downloader:
    image: liubangjian/web-video-downloader:latest
    container_name: web-video-downloader
    ports:
      - "8787:8787"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PORT=8787
      - DOWNLOAD_DIR=/app/downloads
    restart: unless-stopped