version: '3.8'

services:
  douyin-web-video-downloader:
    build: .
    image: liubangjian/douyin-web-video-downloader:latest
    container_name: douyin-web-video-downloader
    ports:
      - "8787:8787"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PORT=8787
      - DOWNLOAD_DIR=/app/downloads
    restart: unless-stopped
